version: "3"
services:
  varnish:
    image: varnish:stable
    container_name: varnish
    volumes:
      - "./docker/varnish/default.vcl:/etc/varnish/default.vcl"
    ports:
      - "81:81"
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G  
    command: "-p default_keep=300"
    depends_on:
      - "httpd" 
  httpd:
    image: httpd:latest
    container_name: httpd
    ports:
      - "8080:81"
